
services:
  clima-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clima-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
