
services:
  clima-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clima-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
